---
#
# file: tasks/install-node-exporter.yml
#

- name: download and untar node_exporter tarball
  unarchive:
    src: "{{ node_exporter_tarball }}"
    dest: "{{ prometheus_install_path }}"
    remote_src: yes
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  tags:
    - tar

- name: copy node_exporter systemd config to server
  template:
    src: "node_exporter.service.j2"
    dest: "/etc/systemd/system/node_exporter.service"
    mode: "a+x"
