---
#
# file: tests/monitoring_stop.yml
#

- hosts: localhost
  connection: local
  become: True
  tasks:
  - name: run daemon-reload
    command: systemctl daemon-reload

- hosts: localhost
  connection: local
  become: True
  tasks:
  - name: stop node_exporter
    systemd: name=node_exporter state=stopped

- hosts: localhost
  connection: local
  become: True
  tasks:
  - name: stop Grafana server
    systemd: name=grafana-server state=stopped

- hosts: localhost
  connection: local
  become: True
  tasks:
  - name: stop Prometheus server
    systemd: name=prometheus state=stopped
