---
#
# file: tests/monitoring_start.yml
#

- hosts: localhost
  connection: local
  become: True
  tasks:
  - name: run daemon-reload
    command: systemctl daemon-reload

- hosts: localhost
  connection: local
  become: True
  tasks:
  - name: start node_exporter
    systemd: name=node_exporter state=started

- hosts: localhost
  connection: local
  become: True
  tasks:
  - name: start Prometheus server
    systemd: name=prometheus state=started

- hosts: localhost
  connection: local
  become: True
  tasks:
  - name: start Grafana server
    systemd: name=grafana-server state=started
